---
title: "Introduction to iSEEid"
author: 
  - name: Federico Marini
    affiliation:
    - Institute of Medical Biostatistics, Epidemiology and Informatics (IMBEI), University Medical Center Mainz, Germany
    - Research Center for Immunotherapy (FZI), Mainz, Germany
    email: marinif@uni-mainz.de
  - name: Kevin Rue-Albrecht
    affiliation:
    - University of Oxford, Oxford, United Kingdom
    email: kevin.rue-albrecht@imm.ox.ac.uk
  - name: Charlotte Soneson
    affiliation:
    - Friedrich Miescher Institute for Biomedical Research, Basel, Switzerland
    - SIB Swiss Institute of Bioinformatics
    email: charlottesoneson@gmail.com
output: 
  BiocStyle::html_document:
    self_contained: yes
    toc: true
    toc_float: true
    toc_depth: 2
    code_folding: show
date: "`r doc_date()`"
package: "`r pkg_ver('iSEEid')`"
vignette: >
  %\VignetteIndexEntry{Introduction to iSEEid}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
bibliography: bibliography_iSEEid.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library("iSEEid")
```

# Quick start to using `iSEEid`

This is a basic example [@kra2018iSEE]

# Session info {-}

```{r}
sessionInfo()
```

# Bibliography
